name: On Pull Request Create
on:
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Restore/cache npm packages
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-packages
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
  deploy:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Deploy to Netlify
        id: netlify-deploy
        run: |
          output_json=$(npx --no-install netlify deploy --auth=${{ secrets.NETLIFY_ACCESS_TOKEN }} --json)
          output_json="${output_json//$'\n'/\\n}"
          echo "::set-output name=output-json::$output_json"
      - name: Find Deploy Result Comment
        id: find-deploy-result-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: has been deployed to Netlify. 
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-deploy-result-comment.outputs.comment-id }}
          body: |
            :rocket: Commit `${{ github.event.pull_request.head.sha }}` has been deployed to Netlify.
            
            - URL: ${{ fromJSON(steps.netlify-deploy.outputs.output-json).deploy_url }}
            - Logs: ${{ fromJSON(steps.netlify-deploy.outputs.output-json).logs }}

