name: On Pull Request Create
on:
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Restore/cache npm packages
        uses: actions/cache@v2
        env:
          cache-name: npm-packages
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            netlify
            public
  deploy:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Find Deploy Result Comment
        id: find-deploy-result-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "- Commit hash: "
          direction: last
      - name: Update Deploy Result Comment - Started
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-deploy-result-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            :gear: Deployment has been started.

            - Commit hash: `${{ github.event.pull_request.head.sha }}`
      - name: Restore/Cache npm Packages
        uses: actions/cache@v2
        env:
          cache-name: npm-packages
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm Packages
        run: npm ci
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Deploy to Netlify
        id: netlify-deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: echo "::set-output name=output_json::$(npx netlify deploy --json | tr -d '\n')"
      - name: Debug
        run: |
          echo "${{ fromJSON(steps.netlify-deploy.outputs.output_json).deploy_url }}"
          echo "${{ fromJSON(steps.netlify-deploy.outputs.output_json).logs }}"
      - name: Update Deploy Result Comment - Finished
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-deploy-result-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            :rocket: The build has been deployed to Netlify.

            - Commit hash: `${{ github.event.pull_request.head.sha }}`
            - URL: ${{ fromJSON(steps.netlify-deploy.outputs.output_json).deploy_url }}
            - Logs: ${{ fromJSON(steps.netlify-deploy.outputs.output_json).logs }}
      - name: Update Deploy Result Comment - Failed
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-deploy-result-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            :warning: Deployment has failed!

            - Commit hash: `${{ github.event.pull_request.head.sha }}`
            - GitHub Action: https://github.com/${{ github.repository }}/runs/${{ github.run_id }}
